# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZhaoPin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=500)),
                ('pname', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('ptype', models.CharField(max_length=50)),
                ('welfare', models.CharField(max_length=300)),
                ('smoney', models.IntegerField()),
                ('emoney', models.IntegerField()),
                ('year', models.IntegerField()),
                ('age', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('time_pub', models.CharField(max_length=100)),
                ('desc_job', models.TextField()),
                ('crawl_time', models.DateField()),
                ('webname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'liepin',
            },
        ),
    ]
